export const CAMERA_OPTIONS = [
    "iPhone 15 Pro Cinematic",
    "Sony A7 IV - 35mm f/1.8",
    "Canon EOS R5 - 85mm f/1.2",
    "Fujifilm X-T4 - Nostalgic Film Sim",
    "Leica M11 - Street Photography",
    "Hasselblad X2D - High Fashion",
    "Nikon Z9 - Action Shot",
    "Panasonic Lumix S1H - Anamorphic Look",
    "RED Komodo 6K - Cinema Grade",
    "Arri Alexa Mini - Film Look",
    "Vintage Super 8mm Film",
    "GoPro Hero 12 - POV Action",
    "Drone Aerial Shot - DJI Mavic 3",
    "DSLR with Creamy Bokeh",
    "Grainy 35mm Film",
    "Black and White Noir",
    "Lomography Fisheye",
    "Macro Lens - Extreme Detail",
    "Tilt-Shift Miniature World",
    "Infrared Photography Effect",
    "Disposable Camera Flash Look",
    "Polaroid Instant Photo",
    "Soft Focus Dreamy Look",
    "High Shutter Speed - Frozen Motion",
    "Long Exposure - Light Trails",
    "Dutch Angle - Tense Mood",
    "Wes Anderson - Symmetrical Style",
    "Paparazzi Flash Photography",
    "Low-fi VHS Camcorder",
    "Thermal Imaging Effect",
    "Glimmerglass Filter - Ethereal Glow",
    "Split Diopter - Near & Far Focus",
    "Telephoto Lens - Compressed Background",
    "Wide Angle Lens - Expansive View",
    "Lens Flare - Golden Hour",
    "Cross-Process Film Look",
    "CCTV Security Camera",
    "Night Vision Effect",
    "1990s Sitcom Look",
    "Glowy, Hazy, Bloom Effect",
    "Sharp & Crisp Commercial Look",
    "Saturated & Vibrant Travel Vlog",
    "Muted & Moody Cinematic Tone",
    "Clean & Bright Tech Review",
    "Handheld Shaky-cam Documentary",
    "Smooth Gimbal Stabilization",
    "Rack Focus Effect",
    "Split Screen Composition",
    "Time-lapse Sequence",
    "Slow-motion Dramatic Shot"
];

export const MOOD_OPTIONS = [
    "GRWM (Get Ready With Me)",
    "Unboxing Excitement",
    "Antusias",
    "Aesthetic Cafe Vlog",
    "Cozy Gaming Stream",
    "High-Energy Workout",
    "DIY Craft Tutorial",
    "ASMR Relaxation",
    "Comedy Skit Vibe",
    "Day in the Life",
    "Honest Product Review",
    "Travel Diary Wanderlust",
    "First Impressions Reaction",
    "Q&A Session Chill",
    "Life Hack / Tips & Tricks",
    "Luxury & Aspirational",
    "Cozy & Relatable",
    "Minimalist & Clean",
    "Dark Academia",
    "Cottagecore / Nature",
    "Y2K / Retro Nostalgia",
    "Streetwear / Hypebeast",
    "Tech & Gadgets",
    "Informative & Educational",
    "Motivational & Inspiring",
    "Chaotic & Funny",
    "Storytime / Narrative",
    "Dance Challenge Trend",
    "Satisfying & Mesmerizing",
    "Foodie / Mukbang",
    "Bookworm / Study Vibe",
    "Artsy & Creative",
    "Spooky & Mysterious",
    "Glamorous & Confident",
    "Authentic & Candid",
    "Heartfelt & Emotional",
    "Sarcastic & Witty",
    "Family Friendly & Wholesome",
    "Adventure & Exploration",
    "Mindfulness & Meditation",
    "Pop Culture Commentary",
    "Celebration / Party Vibe",
    "Behind the Scenes",
    "Couple Goals / Relationship",
    "Pet Antics",
    "Transformative Makeover",
    "Epic Fail Compilation",
    "Science Experiment",
    "Car Enthusiast",
    "Shopping Haul",
    "What I Eat in a Day"
];

export const LOCATION_TYPE_OPTIONS = [
    "Indoor",
    "Outdoor"
];

export const STUDIO_MINI_LOCATIONS = [
    "Sudut dengan dinding bata putih dan karpet bulu putih halus.",
    "Latar belakang kain putih bergelombang dengan properti vas keramik kecil.",
    "Alas kayu dengan backdrop krem polos dan pencahayaan hangat.",
    "Karpet putih lembut dengan lentera mini dan tanaman hijau kecil.",
    "Dinding bertekstur putih dengan bingkai lengkung estetik.",
    "Setup minimalis di atas nampan kayu dengan irisan buah lemon.",
    "Latar belakang tirai putih tipis dengan cahaya matahari sore.",
    "Meja marmer putih dengan properti bunga tulip kuning.",
    "Lantai berbulu abu-abu dengan backdrop dinding bata putih.",
    "Setup dengan kain satin yang tergerai dan pencahayaan lembut.",
    "Properti balok-balok kayu dengan latar belakang dinding beton polos.",
    "Cermin kecil di atas karpet berbulu dengan pantulan cahaya.",
    "Latar belakang kain goni dengan properti bunga kering.",
    "Meja samping tempat tidur dengan buku dan secangkir kopi.",
    "Setup di atas pasir putih halus dengan cangkang kerang.",
    "Backdrop akrilik bening dengan efek riak air.",
    "Latar belakang kertas berwarna pastel yang digulung.",
    "Permukaan cermin dengan pantulan produk dan langit.",
    "Setup di atas tangga kayu dekoratif dengan tanaman merambat.",
    "Alas kain linen kusut dengan pencahayaan natural.",
    "Dinding dengan panel kayu vertikal dan pencahayaan dari samping.",
    "Properti piringan hitam dan cover album retro.",
    "Latar belakang kain beludru berwarna gelap untuk kesan mewah.",
    "Setup di ambang jendela dengan pemandangan taman buram.",
    "Meja rias minimalis dengan beberapa item makeup sebagai properti.",
    "Alas bebatuan alam dengan lumut hijau.",
    "Latar belakang kain sutra yang ditiup angin lembut.",
    "Setup dengan properti geometris seperti kubus dan bola.",
    "Dinding dengan bayangan dedaunan dari jendela.",
    "Lantai keramik estetik dengan pola vintage.",
    "Setup di atas tumpukan majalah fashion.",
    "Backdrop kain tile transparan dengan lampu-lampu kecil.",
    "Meja kayu dengan serbuk kopi dan biji kopi tersebar.",
    "Alas kain kotak-kotak piknik dengan properti keranjang rotan.",
    "Dinding dicat setengah, bagian bawah berwarna, atas putih.",
    "Setup dengan properti mangkuk keramik berisi air.",
    "Latar belakang dinding ombre dengan gradasi warna lembut.",
    "Permukaan air tenang yang memantulkan produk.",
    "Setup di atas rumput sintetis hijau dengan bunga aster.",
    "Kain gantung macrame sebagai latar belakang.",
    "Meja kerja dengan laptop, kacamata, dan notes.",
    "Latar belakang kertas koran atau halaman buku tua.",
    "Setup dengan properti kaca pembesar untuk menonjolkan detail.",
    "Alas kain wol tebal dengan tekstur chunky.",
    "Dinding bata ekspos dengan pencahayaan industrial.",
    "Setup dengan properti benang rajut dan jarum.",
    "Latar belakang kain dengan motif cat air abstrak.",
    "Meja dengan properti set catur dari kayu.",
    "Setup di atas ayunan rotan gantung.",
    "Latar belakang proyektor yang menampilkan pola abstrak.",
    "Alas beton kasar dengan latar belakang kain linen berwarna netral.",
    "Setup dengan properti busa geometris (lengkungan, tangga) berwarna pastel.",
    "Latar belakang terakota dengan bayangan daun palem yang tajam.",
    "Permukaan berpasir dengan batu-batu sungai halus dan ranting kering.",
    "Nampan akrilik berisi air dengan kelopak bunga mengambang.",
    "Sudut dengan backdrop dua warna, pink pastel dan krem, terpisah secara diagonal.",
    "Kain satin berwarna champagne yang ditata berkerut dengan elegan.",
    "Balok kaca bening dengan distorsi cahaya yang menarik.",
    "Latar belakang bertekstur plesteran dinding dengan gaya wabi-sabi.",
    "Meja kayu jati tua dengan properti cangkir keramik buatan tangan.",
    "Alas kain waffle berwarna off-white dengan beberapa biji kapas.",
    "Latar belakang ubin keramik kecil berwarna hijau sage.",
    "Properti piringan keramik berputar dengan tanah liat basah.",
    "Setup di atas papan catur marmer hitam dan putih.",
    "Kain tipis digantung di depan sumber cahaya untuk efek halo.",
    "Latar belakang kertas sobek dengan tepi tidak rata, menunjukkan lapisan warna.",
    "Permukaan cermin pecah yang disusun kembali secara artistik.",
    "Setup dengan es batu dan daun mint segar (untuk produk minuman).",
    "Latar belakang kain tenun tradisional dengan pola etnik.",
    "Blok es besar yang perlahan mencair, dengan produk di dekatnya.",
    "Lantai kayu parket dengan cahaya jendela yang membentuk garis-garis.",
    "Setup dengan properti prisma yang memecah cahaya menjadi pelangi.",
    "Latar belakang kain berwarna gradien dari biru muda ke oranye senja.",
    "Mangkuk kayu berisi berbagai rempah-rempah kering.",
    "Permukaan logam yang disikat (brushed metal) dengan pantulan lembut.",
    "Kain beludru berwarna biru royal untuk nuansa mewah dan dalam.",
    "Setup di atas tumpukan buku-buku antik dengan sampul kulit.",
    "Latar belakang panel akrilik berwarna-warni yang tembus cahaya.",
    "Alas rumput pampas kering yang lembut.",
    "Setup dengan properti awan buatan dari kapas.",
    "Latar belakang dinding yang belum selesai dicat, dengan bekas rol cat.",
    "Permukaan air dengan riak yang disebabkan oleh tetesan.",
    "Properti kerang abalon dengan kilau warna-warni.",
    "Latar belakang jaring ikan yang digantung secara longgar.",
    "Alas yang ditutupi kelopak bunga mawar merah.",
    "Setup dengan properti pasir kinetik.",
    "Latar belakang kertas marmer buatan tangan.",
    "Balok kayu yang dibakar sebagian (teknik Shou Sugi Ban).",
    "Latar belakang tirai manik-manik kristal.",
    "Setup di dalam kotak kayu dengan serutan kayu sebagai alas.",
    "Permukaan yang ditutupi oleh foil emas atau perak yang diremas.",
    "Latar belakang kain shibori (teknik ikat celup Jepang).",
    "Properti sarang burung kecil dengan beberapa telur puyuh.",
    "Setup di atas lempengan batu tulis dengan goresan kapur.",
    "Latar belakang yang terbuat dari susunan stik es krim kayu.",
    "Alas dari lumut hijau yang diawetkan.",
    "Setup dengan properti geode atau kristal batu.",
    "Latar belakang kain berlubang dengan cahaya dari belakang.",
    "Permukaan terrazzo dengan serpihan warna-warni.",
    "Latar belakang dari pantulan bola disko mini."
];

export const INDOOR_LOCATIONS = [
    "Angkringan (Bagian Dalam)",
    "Apotek",
    "Aquarium Indoor Raksasa",
    "Arena Bermain Anak Indoor",
    "Arena Bowling",
    "Arena Gelanggang Es",
    "Arsip Nasional atau Daerah",
    "Aula Balai Desa",
    "Aula Pernikahan",
    "Aula Sekolah",
    "Balkon Apartemen Tertutup",
    "Bandara (Ruang Tunggu)",
    "Barber Shop Retro",
    "Bengkel Las",
    "Bengkel Mobil",
    "Bengkel Motor Pinggir Jalan",
    "Bengkel Pengrajin Perak",
    "Bengkel Ukir Kayu",
    "Bioskop",
    "Biro Perjalanan",
    "Bongkaran Gedung Tua",
    "Butik Pakaian Desainer Lokal",
    "Cafe dengan Live Music",
    "Cafe Rooftop (Bagian Indoor)",
    "Cukur Rambut di Bawah Pohon (Semi-Indoor)",
    "Dalam Bajaj atau Angkot",
    "Dalam Bis Kota",
    "Dalam KRL Commuter Line",
    "Dalam Lift Gedung Perkantoran",
    "Dalam Mobil",
    "Dalam Taksi Online",
    "Dapur Food Truck",
    "Dapur Kursus Masak",
    "Dapur Restoran Sibuk",
    "Dapur Rumah Modern",
    "Dapur Rumah Sederhana",
    "Distro Baju",
    "Es Krim & Gelato Shop",
    "Food Court Mall",
    "Galeri Foto Jurnalistik",
    "Galeri Seni Kontemporer",
    "Gedung Kesenian",
    "Gedung Olahraga (GOR)",
    "Gereja Kuno",
    "Gereja Modern",
    "Greenhouse atau Rumah Kaca",
    "Gudang Ekspedisi",
    "Gudang Kosong",
    "Gym Center",
    "Home Studio (Musik/Podcast)",
    "Hotel Kapsul",
    "Interior Bus Malam",
    "Interior Gereja Katedral",
    "Interior Istana",
    "Interior Kapal Feri",
    "Interior Kereta Api Eksekutif",
    "Interior Kereta Api Ekonomi",
    "Interior Masjid Agung",
    "Interior Masjid Desa",
    "Interior Pura Bali",
    "Interior Rumah Adat (Joglo, Gadang, dll)",
    "Interior Rumah Sakit",
    "Interior Villa Mewah",
    "Kamar Anak Kuliahan",
    "Kamar Anak SMA",
    "Kamar Bayi",
    "Kamar Ganti Atlet",
    "Kamar Hotel Bintang Lima",
    "Kamar Hotel Melati",
    "Kamar Kos Mahasiswa",
    "Kamar Mandi Estetik",
    "Kamar Tidur Utama Mewah",
    "Kamar Tidur Utama Sederhana",
    "Kantor Akuntan Publik",
    "Kantor Bank",
    "Kantor Desa",
    "Kantor Notaris",
    "Kantor Pemerintahan",
    "Kantor Polisi (Ruang Pelayanan)",
    "Kantor Pos",
    "Kantor Redaksi Media",
    "Kantor Start-up",
    "Kantin Karyawan",
    "Kantin Sekolah",
    "Kafe Kopi Kekinian",
    "Kafe Minimalis",
    "Kedai Jamu",
    "Kedai Kopi di Hutan Pinus (Bagian Indoor)",
    "Kelenteng",
    "Klinik Dokter Gigi",
    "Klinik Dokter Umum",
    "Klinik Kecantikan",
    "Klub Malam",
    "Kolam Renang Indoor",
    "Konter Pulsa & Aksesoris HP",
    "Koperasi Unit Desa (KUD)",
    "Koridor Apartemen",
    "Koridor Sekolah",
    "Laboratorium Bahasa",
    "Laboratorium Komputer",
    "Laboratorium Penelitian",
    "Lobi Apartemen",
    "Lobi Gedung Perkantoran",
    "Lobi Hotel",
    "Loft Bergaya Industri",
    "Masjid Kampus",
    "Museum Nasional",
    "Museum Perjuangan",
    "Museum Transportasi",
    "Museum Wayang",
    "Observatorium",
    "Pabrik Garmen",
    "Pabrik Kerupuk",
    "Pabrik Rokok Kretek",
    "Pabrik Tahu atau Tempe",
    "Panggung Teater",
    "Panti Asuhan",
    "Panti Jompo",
    "Pasar Loak Indoor",
    "Pasar Swalayan (Supermarket)",
    "Pendopo Rumah Jawa",
    "Pengadilan (Ruang Sidang)",
    "Penjahit Pakaian",
    "Perpustakaan Daerah",
    "Perpustakaan Kampus",
    "Perpustakaan Nasional",
    "Pesantren (Ruang Belajar)",
    "Pet Shop",
    "Planetarium",
    "Pujasera (Pusat Jajanan Serba Ada)",
    "Pusat Kebugaran",
    "Puskesmas",
    "Rental Komputer & Game Online",
    "Rental PS",
    "Restoran Cepat Saji",
    "Restoran Chinese Food",
    "Restoran Hotel",
    "Restoran Jepang",
    "Restoran Padang",
    "Ruang Arsip",
    "Ruang Baca Publik",
    "Ruang Biliar",
    "Ruang Ganti Gym",
    "Ruang Ganti Toko Pakaian",
    "Ruang Karaoke",
    "Ruang Kelas SD",
    "Ruang Kelas TK",
    "Ruang Kelas Universitas",
    "Ruang Konseling",
    "Ruang Meeting Co-working Space",
    "Ruang Musik Sekolah",
    "Ruang Rapat Kantor",
    "Ruang Santai Kantor (Pantry)",
    "Ruang Server",
    "Ruang Tamu Mewah",
    "Ruang Tamu Sederhana",
    "Ruang Tunggu Bengkel",
    "Ruang Tunggu Stasiun",
    "Rumah Makan Seafood Tepi Pantai (Indoor)",
    "Rumah Makan Sunda Lesehan",
    "Rumah Produksi Film (Post-production)",
    "Rumah Susun Sederhana (Interior)",
    "Saung Bambu",
    "Salon Kecantikan",
    "Sanggar Lukis",
    "Sanggar Tari Tradisional",
    "Sekretariat Organisasi Mahasiswa",
    "Stasiun Kereta Bawah Tanah (MRT)",
    "Studio Animasi",
    "Studio Foto",
    "Studio Lukis",
    "Studio Podcast",
    "Studio Radio",
    "Studio Rekaman Musik",
    "Studio TV Lokal",
    "Taman Bacaan Masyarakat",
    "Tempat Cuci Mobil (Area Tunggu)",
    "Tempat Fotokopi",
    "Tempat Ibadah (Umum)",
    "Tempat Kursus Bahasa Asing",
    "Tempat Latihan Band",
    "Toko Alat Musik",
    "Toko Alat Tulis Kantor (ATK)",
    "Toko Bahan Kue",
    "Toko Bangunan",
    "Toko Barang Antik",
    "Toko Buku",
    "Toko Elektronik",
    "Toko Emas",
    "Toko Grosir",
    "Toko Kain",
    "Toko Kaset dan Vinyl Bekas",
    "Toko Kelontong",
    "Toko Komputer",
    "Toko Mainan",
    "Toko Oleh-oleh",
    "Toko Optik",
    "Toko Perlengkapan Bayi",
    "Toko Perlengkapan Mendaki",
    "Toko Roti & Kue",
    "Toko Sepatu",
    "Toko Seragam Sekolah",
    "Toko Sparepart Otomotif",
    "Toko Sport",
    "Toko Tanaman Hias",
    "Vihara",
    "Warung Indomie (Warmindo)",
    "Warung Kopi (Warkop) Tradisional",
    "Warung Makan Pinggir Jalan (Bagian Dalam)",
    "Warteg (Warung Tegal)",
    "Workshop Pengrajin Kulit"
];

export const OUTDOOR_LOCATIONS = [
    "Air Terjun di Hutan",
    "Alun-alun Kota",
    "Amfiteater Terbuka",
    "Area Api Unggun Perkemahan",
    "Area Balap Liar (Malam Hari)",
    "Area Car Free Day",
    "Area Parkir Motor Penuh Sesak",
    "Area Parkir Truk",
    "Area Pembuatan Garam Tradisional",
    "Area Pembuatan Kapal Pinisi",
    "Area Piknik di Taman Kota",
    "Area Tambang Belerang",
    "Atap Gedung Tua (Rooftop)",
    "Balkon Apartemen",
    "Bantaran Rel Kereta Api",
    "Bantaran Sungai di Perkotaan",
    "Bawah Jembatan Layang (Flyover)",
    "Blok Sawah yang Baru Dibajak",
    "Bukit Berbatu",
    "Bukit Kapur",
    "Bukit Menghadap Laut",
    "Bukit Savana",
    "Bumi Perkemahan",
    "Candi Tersembunyi di Hutan",
    "Danau Kawah Vulkanik",
    "Delta Sungai",
    "Dermaga Feri",
    "Dermaga Kayu Kecil",
    "Desa di Atas Awan",
    "Desa di Lereng Gunung",
    "Desa Nelayan",
    "Festival Layang-layang",
    "Festival Musik Outdoor",
    "Gang Sempit di Perkampungan",
    "Gerbang Kompleks Perumahan",
    "Gerbang Tol",
    "Goa Pesisir",
    "Halte Bus",
    "Halte Busway Ramai",
    "Halaman Belakang Rumah",
    "Halaman Gereja",
    "Halaman Masjid Agung",
    "Halaman Rumah dengan Ayunan",
    "Halaman Sekolah saat Istirahat",
    "Helipad di Atas Gedung",
    "Hutan Bambu",
    "Hutan Karet",
    "Hutan Mangrove",
    "Hutan Mati (Bekas Terbakar)",
    "Hutan Pinus",
    "Hutan Tropis",
    "Jalan Berkelok di Pegunungan",
    "Jalan Desa yang Sepi",
    "Jalan Ditepi Jurang",
    "Jalan di Dalam Terowongan",
    "Jalan di Kawasan Industri",
    "Jalan di Perkebunan",
    "Jalan Layang (Flyover)",
    "Jalan Macet di Jam Sibuk",
    "Jalan Protokol Kota Besar",
    "Jalan Setapak di Bukit",
    "Jalan Setapak di Hutan",
    "Jalan Sempit Antar Gedung",
    "Jalan Tol",
    "Jalanan di Depan Pasar",
    "Jalanan di Kawasan Pecinan",
    "Jalanan Kota di Malam Hari",
    "Jalanan Kota saat Hujan",
    "Jembatan Akar",
    "Jembatan Bambu di Atas Sungai",
    "Jembatan Besi Tua",
    "Jembatan Gantung Sederhana",
    "Jembatan Kayu di Atas Rawa",
    "Jembatan Penyeberangan Orang (JPO)",
    "Jembatan Tol Ikonik",
    "Jogging Track di Taman",
    "Kaki Lima Penjual Makanan",
    "Kandang Kuda",
    "Kampung Adat",
    "Kampung di Atas Air",
    "Kampung Pelangi",
    "Kanal atau Selokan Besar",
    "Kawah Gunung Berapi",
    "Kawasan Kota Tua",
    "Kawasan Wisata Kawah Putih",
    "Kebun Binatang",
    "Kebun Buah (Salak, Jeruk, dll)",
    "Kebun Bunga Matahari",
    "Kebun Kopi",
    "Kebun Sawit",
    "Kebun Sayur Belakang Rumah",
    "Kebun Teh",
    "Kolam Ikan di Desa",
    "Kolam Pemancingan",
    "Kolam Renang Hotel",
    "Kolam Renang Umum",
    "Kompleks Candi",
    "Kompleks Makam Raja",
    "Kompleks Pergudangan",
    "Kompleks Pertokoan (Ruko)",
    "Ladang Jagung",
    "Ladang Tembakau",
    "Lahan Parkir Terbuka Luas",
    "Lapak Pedagang Kaki Lima",
    "Lapangan Badminton Komplek",
    "Lapangan Basket Jalanan",
    "Lapangan Desa",
    "Lapangan Futsal Komplek",
    "Lapangan Golf",
    "Lapangan Upacara Sekolah",
    "Laut Lepas",
    "Lereng Gunung Berapi",
    "Padang Ilalang",
    "Padang Pasir",
    "Panggung Konser Terbuka",
    "Pantai Berpasir Hitam",
    "Pantai Berpasir Putih",
    "Pantai dengan Batu Karang",
    "Pangkalan Ojek",
    "Pasar Apung",
    "Pasar Burung",
    "Pasar Hewan",
    "Pasar Ikan",
    "Pasar Kaget Minggu Pagi",
    "Pasar Malam",
    "Pasar Tumpah di Pinggir Jalan",
    "Pasar Tradisional",
    "Pelabuhan Kontainer",
    "Pelabuhan Nelayan",
    "Pematang Sawah",
    "Pemandian Air Panas Alami",
    "Pembangkit Listrik Tenaga Angin",
    "Penangkaran Penyu",
    "Penyeberangan Getek",
    "Perempatan Jalan dengan Lampu Merah",
    "Perkebunan Cengkeh",
    "Perkebunan Kelapa",
    "Perkebunan Tebu",
    "Perkampungan Baduy",
    "Perlintasan Kereta Api",
    "Perpustakaan Jalanan",
    "Pertigaan Jalan yang Ramai",
    "Perumahan Elit",
    "Perumahan Padat Penduduk",
    "Pesisir Pantai Nelayan",
    "Peternakan Ayam",
    "Peternakan Sapi",
    "Pinggir Jalan Raya",
    "Pos Ronda",
    "Proyek Konstruksi Bangunan",
    "Puncak Bukit untuk Paralayang",
    "Puncak Gunung",
    "Pura di Tepi Danau",
    "Pura di Tepi Tebing",
    "Rawa-rawa",
    "Rel Kereta Api Non-aktif",
    "Rest Area di Jalan Tol",
    "Rooftop Cafe",
    "Rumah Apung di Danau",
    "Sawah yang Menguning",
    "Sawah Terasering",
    "Shelter Ojek Online",
    "Stadion Sepak Bola",
    "Stasiun Kereta Commuter Line",
    "Stasiun Pengisian Bahan Bakar Umum (SPBU)",
    "Sungai di Dalam Hutan",
    "Taman Bunga",
    "Taman Komplek Perumahan",
    "Taman Kota",
    "Taman Lalu Lintas",
    "Taman Makam Pahlawan",
    "Tambak Garam",
    "Tambak Udang",
    "Tangga Batu Kuno Menuju Candi",
    "Tebing Kapur",
    "Tepi Danau",
    "Teras Rumah Perkampungan Indonesia",
    "Terminal Bus Antar Kota",
    "Terminal Peti Kemas",
    "Titik Nol Kilometer",
    "Toko Tanaman di Pinggir Jalan",
    "Trotoar Jalanan Kota",
    "Tugu Peringatan",
    "Underpass atau Terowongan Jalan",
    "Warung Kopi Pinggir Jalan (Warkop)",
    "Warung Lesehan Tenda",
    "Warung Pecel Lele Tenda",
    "Waduk atau Bendungan"
];

export const CAMERA_ANGLE_OPTIONS = [
    "Random (Auto)",
    "Wide Angle Shot",
    "Medium Shot",
    "Close-up Shot",
    "Extreme Close-up",
    "Full Body Shot",
    "Cowboy Shot (Mid-thigh up)",
    "Point of View (POV)",
    "Over the Shoulder Shot",
    "Low Angle Shot",
    "High Angle Shot",
    "Dutch Angle Shot"
];

export const PRODUCT_CATEGORIES = [
    "Elektronik",
    "Makanan & Minuman",
    "Komputer & Aksesoris",
    "Perawatan & Kecantikan",
    "Handphone & Aksesoris",
    "Perlengkapan Rumah",
    "Pakaian Pria",
    "Pakaian Wanita",
    "Sepatu Pria",
    "Fashion Muslim",
    "Tas Pria",
    "Fashion Bayi & Anak",
    "Aksesoris Fashion",
    "Ibu & Bayi",
    "Jam Tangan",
    "Sepatu Wanita",
    "Kesehatan",
    "Tas Wanita",
    "Hobi & Koleksi",
    "Otomotif",
    "Olahraga & Outdoor",
    "Buku & Alat Tulis",
    "Souvenir & Perlengkapan Pesta",
    "Fotografi",
    "Voucher"
];

export const VOICEOVER_STYLE_OPTIONS = [
    "Simpel",
    "Detail"
];