export const CAMERA_OPTIONS = [
    "iPhone 15 Pro Cinematic",
    "Sony A7 IV - 35mm f/1.8",
    "Canon EOS R5 - 85mm f/1.2",
    "Fujifilm X-T4 - Nostalgic Film Sim",
    "Leica M11 - Street Photography",
    "Hasselblad X2D - High Fashion",
    "Nikon Z9 - Action Shot",
    "Panasonic Lumix S1H - Anamorphic Look",
    "RED Komodo 6K - Cinema Grade",
    "Arri Alexa Mini - Film Look",
    "Vintage Super 8mm Film",
    "GoPro Hero 12 - POV Action",
    "Drone Aerial Shot - DJI Mavic 3",
    "DSLR with Creamy Bokeh",
    "Grainy 35mm Film",
    "Black and White Noir",
    "Lomography Fisheye",
    "Macro Lens - Extreme Detail",
    "Tilt-Shift Miniature World",
    "Infrared Photography Effect",
    "Disposable Camera Flash Look",
    "Polaroid Instant Photo",
    "Soft Focus Dreamy Look",
    "High Shutter Speed - Frozen Motion",
    "Long Exposure - Light Trails",
    "Dutch Angle - Tense Mood",
    "Wes Anderson - Symmetrical Style",
    "Paparazzi Flash Photography",
    "Low-fi VHS Camcorder",
    "Thermal Imaging Effect",
    "Glimmerglass Filter - Ethereal Glow",
    "Split Diopter - Near & Far Focus",
    "Telephoto Lens - Compressed Background",
    "Wide Angle Lens - Expansive View",
    "Lens Flare - Golden Hour",
    "Cross-Process Film Look",
    "CCTV Security Camera",
    "Night Vision Effect",
    "1990s Sitcom Look",
    "Glowy, Hazy, Bloom Effect",
    "Sharp & Crisp Commercial Look",
    "Saturated & Vibrant Travel Vlog",
    "Muted & Moody Cinematic Tone",
    "Clean & Bright Tech Review",
    "Handheld Shaky-cam Documentary",
    "Smooth Gimbal Stabilization",
    "Rack Focus Effect",
    "Split Screen Composition",
    "Time-lapse Sequence",
    "Slow-motion Dramatic Shot"
];

export const MOOD_OPTIONS = [
    "GRWM (Get Ready With Me)",
    "Unboxing Excitement",
    "Aesthetic Cafe Vlog",
    "Cozy Gaming Stream",
    "High-Energy Workout",
    "DIY Craft Tutorial",
    "ASMR Relaxation",
    "Comedy Skit Vibe",
    "Day in the Life",
    "Honest Product Review",
    "Travel Diary Wanderlust",
    "First Impressions Reaction",
    "Q&A Session Chill",
    "Life Hack / Tips & Tricks",
    "Luxury & Aspirational",
    "Cozy & Relatable",
    "Minimalist & Clean",
    "Dark Academia",
    "Cottagecore / Nature",
    "Y2K / Retro Nostalgia",
    "Streetwear / Hypebeast",
    "Tech & Gadgets",
    "Informative & Educational",
    "Motivational & Inspiring",
    "Chaotic & Funny",
    "Storytime / Narrative",
    "Dance Challenge Trend",
    "Satisfying & Mesmerizing",
    "Foodie / Mukbang",
    "Bookworm / Study Vibe",
    "Artsy & Creative",
    "Spooky & Mysterious",
    "Glamorous & Confident",
    "Authentic & Candid",
    "Heartfelt & Emotional",
    "Sarcastic & Witty",
    "Family Friendly & Wholesome",
    "Adventure & Exploration",
    "Mindfulness & Meditation",
    "Pop Culture Commentary",
    "Celebration / Party Vibe",
    "Behind the Scenes",
    "Couple Goals / Relationship",
    "Pet Antics",
    "Transformative Makeover",
    "Epic Fail Compilation",
    "Science Experiment",
    "Car Enthusiast",
    "Shopping Haul",
    "What I Eat in a Day"
];

export const LOCATION_TYPE_OPTIONS = [
    "Indoor",
    "Outdoor"
];

export const INDOOR_LOCATIONS = [
    "Kafe Minimalis",
    "Apartemen Modern",
    "Kamar Tidur Estetik",
    "Dapur Bersih",
    "Perpustakaan Cozy",
    "Studio Foto",
    "Ruang Tamu Mewah",
    "Kamar Mandi Spa",
    "Toko Buku Independen",
    "Gym Dalam Ruangan",
    "Galeri Seni",
    "Restoran Elegan",
    "Kantor Rumahan (Home Office)",
    "Area Gaming",
    "Ruang Musik",
    "Greenhouse Dalam Ruangan",
    "Loft Industri",
    "Hotel Butik",
    "Pusat Perbelanjaan",
    "Stasiun Kereta Bawah Tanah"
];

export const OUTDOOR_LOCATIONS = [
    "Jalanan Kota Malam Hari",
    "Pantai Tropis Saat Senja",
    "Taman Kota yang Rindang",
    "Hutan Pinus Berkabut",
    "Puncak Gunung",
    "Rooftop Bar dengan Pemandangan Kota",
    "Jalanan Pedesaan",
    "Area Kolam Renang",
    "Taman Bunga",
    "Pasar Tradisional",
    "Air Terjun Tersembunyi",
    "Padang Rumput Luas",
    "Area Sekitar Danau",
    "Jembatan Ikonik",
    "Kebun Teh",
    "Area Camping",
    "Lapangan Olahraga",
    "Gurun Pasir",
    "Pelabuhan",
    "Sawah Hijau"
];

export const CAMERA_ANGLE_OPTIONS = [
    "Random (Auto)",
    "Wide Angle Shot",
    "Medium Shot",
    "Close-up Shot",
    "Extreme Close-up",
    "Full Body Shot",
    "Cowboy Shot (Mid-thigh up)",
    "Point of View (POV)",
    "Over the Shoulder Shot",
    "Low Angle Shot",
    "High Angle Shot",
    "Dutch Angle Shot"
];

export const PRODUCT_CATEGORIES = [
    "Elektronik",
    "Makanan & Minuman",
    "Komputer & Aksesoris",
    "Perawatan & Kecantikan",
    "Handphone & Aksesoris",
    "Perlengkapan Rumah",
    "Pakaian Pria",
    "Pakaian Wanita",
    "Sepatu Pria",
    "Fashion Muslim",
    "Tas Pria",
    "Fashion Bayi & Anak",
    "Aksesoris Fashion",
    "Ibu & Bayi",
    "Jam Tangan",
    "Sepatu Wanita",
    "Kesehatan",
    "Tas Wanita",
    "Hobi & Koleksi",
    "Otomotif",
    "Olahraga & Outdoor",
    "Buku & Alat Tulis",
    "Souvenir & Perlengkapan Pesta",
    "Fotografi",
    "Voucher"
];

export const VOICEOVER_STYLE_OPTIONS = [
    "Simpel",
    "Detail"
];